language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Q4ZdvsrungR7YK5sG18hgV3AN6p2tNgdFRsJpxj2TWqNb8asU+0DjWHxzzK1+gAdMnsk3b2kOH2sqKsb6m++ZPhpLBADax9H1HC5HR3hu8BbSws0ePgHz/nsI9UgulmGBKTYpOzSt/d3AaIw8P6gCFQNQGwOPKKZfleVKVKPST2Th5ovBUBO3Yicudc0U4r9cEyfGTSsF68Ogvb3y0P3BRuOQX1LN+Qyq3Nyhk/Xon33ftqz7WJbcMxKknYFpIvCanP86sgnUT321hwgAi1mzScqsTZBuzScSbdM6skjJdlwdkA7E/2yFF6XVt7SVqFSoNQ+N26D+KPFDKOcVmjHYNGuBybPhhWdvOwDO0EacDZsulMvttHBhILN/g+d5KyIt7hGNFDdPllgwYO5FRCyrL+uSMxpgkHi1HHHlOuREi+RUze2djEGuPoueW72ZpmFVoo6afd2H0xZ1vAjOofB4+SswF1JO+bH5k63ge38fyaOm+qIsH6oQfALGt0TdhORuWHk5vsznBOXSJ3vYkiZWtCl4TsoGifoMwkz3ju1Z04xnIfdqoGb3Q3unoNthmis5ZlC4vcN6GDrZI33H4XzAhLgNzeZzWhaE7XEUf2aKmyFbX64IjPtUXvTYVPexH07jVgTxvlfRDoFJTD+YIgsfugKmdNkGKvUfBiZ1QNe9+k=
  app: license-management